export const contracts = [
            { name: 'Side', description: 'Il faut planter 3 fléchettes dans 3 secteurs qui se touchent (Ex : 16, 7, 19).' },

        { name: '20', description: 'Il faut faire au moins un 20.' },
        { name: 'Suite', description: 'Il faut planter 3 fléchettes dans 3 numéros qui se suivent (ex : 20-19-18).' },      
        { name: '19', description: 'Il faut faire au moins un 19.' },
        { name: 'Side', description: 'Il faut planter 3 fléchettes dans 3 secteurs qui se touchent (Ex : 16, 7, 19).' },
        { name: '18', description: 'Il faut faire au moins un 18.' }, 
        { name: 'Couleur', description: 'Il faut planter 3 fléchettes sur trois couleurs différentes (ex : 20-19-triple 20 => noir-blanc-rouge).' },    
        { name: '17', description: 'Il faut faire au moins un 17.' },
        { name: '57', description: 'Il faut effectuer un total de 57 points (ex : 19-double 19 => 19 + 2 x 19 = 57).' },
        { name: '16', description: 'Il faut faire au moins un 16.' },
        { name: "Peluche", description: 'Il faut planter les 3 fléchettes et faire un score inférieur ou égale à 20.' },
        { name: '15', description: 'Il faut faire au moins un 15.' },
        { name: 'Triple', description: 'Il faut faire au moins un Triple.' },
        { name: '14', description: 'Il faut faire au moins un 14.' },
        { name: 'Double', description: 'Il faut faire au moins un Double.' },
        { name: '13', description: 'Il faut faire au moins un 13.' },
        { name: 'Centre', description: 'Il faut faire au moins un centre (bull=50 ou 1/2 bull=25).' },
      ]