export const contracts = [
  { name: "20", descriptionKey: "contracts.20" },
  { name: "Suite", descriptionKey: "contracts.Suite" },
  { name: "19", descriptionKey: "contracts.19" },
  { name: "Side", descriptionKey: "contracts.Side" },
  { name: "18", descriptionKey: "contracts.18" },
  { name: "Couleur", descriptionKey: "contracts.Couleur" },
  { name: "17", descriptionKey: "contracts.17" },
  { name: "57", descriptionKey: "contracts.57" },
  { name: "16", descriptionKey: "contracts.16" },
  { name: "Peluche", descriptionKey: "contracts.Peluche" },
  { name: "15", descriptionKey: "contracts.15" },
  { name: "Triple", descriptionKey: "contracts.Triple" },
  { name: "14", descriptionKey: "contracts.14" },
  { name: "Double", descriptionKey: "contracts.Double" },
  { name: "13", descriptionKey: "contracts.13" },
  { name: "Centre", descriptionKey: "contracts.Centre" },
];
